export const LOAD_BALANCERS_FIELD_NAMES = Object.freeze({
  IS_HAPROXY_ENABLED: 'isHaproxyEnabled',
  IS_DEPLOY_TO_DATABASE_SERVERS: 'isDeployToDatabaseServers',
  LOAD_BALANCER_DATABASES: 'loadBalancerDatabases',
  LOAD_BALANCER_DATABASES_HOSTNAME: 'loadBalancerDatabasesHostname',
  LOAD_BALANCER_DATABASES_IP_ADDRESS: 'loadBalancerDatabasesIpAddress',
});

export const LOAD_BALANCERS_DATABASES_DEFAULT_VALUES = Object.freeze({
  [LOAD_BALANCERS_FIELD_NAMES.LOAD_BALANCER_DATABASES_HOSTNAME]: '',
  [LOAD_BALANCERS_FIELD_NAMES.LOAD_BALANCER_DATABASES_IP_ADDRESS]: '',
});
