---
- name: Fetch TLS certificate, key and CA from the master node into memory
  run_once: true
  ansible.builtin.slurp:
    src: "{{ item }}"
  delegate_to: "{{ groups.master[0] }}"
  register: tls_files
  loop:
    - "{{ tls_privatekey_path | default('/etc/tls/server.key') }}"
    - "{{ tls_cert_path | default('/etc/tls/server.crt') }}"
    - "{{ tls_ca_cert_path | default('/etc/tls/ca.crt') }}"
  tags: tls, tls_cert_copy

- name: Create directory {{ copy_tls_privatekey_path | default(tls_privatekey_path | default('/etc/tls/server.key')) | dirname }}
  ansible.builtin.file:
    path: "{{ copy_tls_privatekey_path | default(tls_privatekey_path | default('/etc/tls/server.key')) | dirname }}"
    state: directory
    owner: "{{ copy_tls_owner | default(tls_owner | default('postgres')) }}"
    group: "{{ copy_tls_owner | default(tls_owner | default('postgres')) }}"
    mode: "0755"
  tags: tls, tls_cert_copy

- name: Copy PostgreSQL TLS certificate, key and CA to all nodes
  ansible.builtin.copy:
    content: "{{ tls_files.results[item.index].content | b64decode }}"
    dest: "{{ item.path }}"
    owner: "{{ copy_tls_owner | default(tls_owner | default('postgres')) }}"
    group: "{{ copy_tls_owner | default(tls_owner | default('postgres')) }}"
    mode: "{{ item.mode }}"
  loop:
    - { index: 1, path: "{{ copy_tls_cert_path | default(tls_cert_path | default('/etc/tls/server.crt')) }}", mode: "0644" }
    - { index: 2, path: "{{ copy_tls_ca_cert_path | default(tls_ca_cert_path | default('/etc/tls/ca.crt')) }}", mode: "0644" }
    - { index: 0, path: "{{ copy_tls_privatekey_path | default(tls_privatekey_path | default('/etc/tls/server.key')) }}", mode: "0400" }
  tags: tls, tls_cert_copy
