---
pgdg_architecture_map:
  amd64: x86_64
  x86_64: x86_64
  aarch64: aarch64

# Extension Auto-Setup:
pgvectorscale_architecture_map:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64

paradedb_architecture_map_dep:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64

paradedb_architecture_map_rpm:
  x86_64: x86_64
  amd64: x86_64
  aarch64: aarch64
  arm64: aarch64
