---
# {{ ansible_managed }}

# This requires the pg_stat_statements module (disabled by default)
# https://www.postgresql.org/docs/9.6/static/pgstatstatements.html
pg_stat_statements:
  metrics:
    - rolname:
      description: "Name of the user who executed the statement"
      usage: LABEL
    - datname:
      description: "Name of the database"
      usage: "LABEL"
    - queryid:
      description: Internal hash code, computed from the statement's parse tree
      usage: LABEL
    - query:
      description: Text of a representative statement
      usage: LABEL
    - calls:
      description: Number of times executed
      usage: COUNTER
    - total_time:
      description: Total time spent in the statement, in milliseconds
      usage: COUNTER
    - min_time:
      description: Minimum time spent in the statement, in milliseconds
      usage: COUNTER
    - max_time:
      description: Maximum time spent in the statement, in milliseconds
      usage: COUNTER
    - mean_time:
      description: Mean time spent in the statement, in milliseconds
      usage: COUNTER
    - stddev_time:
      description: >-
        Population standard deviation of time spent in the statement, in
        milliseconds
      usage: COUNTER
    - rows:
      description: Total number of rows retrieved or affected by the statement
      usage: COUNTER
    - shared_blks_hit:
      description: Total number of shared block cache hits by the statement
      usage: COUNTER
    - shared_blks_read:
      description: Total number of shared blocks read by the statement
      usage: COUNTER
    - shared_blks_dirtied:
      description: Total number of shared blocks dirtied by the statement
      usage: COUNTER
    - shared_blks_written:
      description: Total number of shared blocks written by the statement
      usage: COUNTER
    - local_blks_hit:
      description: Total number of local block cache hits by the statement
      usage: COUNTER
    - local_blks_read:
      description: Total number of local blocks read by the statement
      usage: COUNTER
    - local_blks_dirtied:
      description: Total number of local blocks dirtied by the statement
      usage: COUNTER
    - local_blks_written:
      description: Total number of local blocks written by the statement
      usage: COUNTER
    - temp_blks_read:
      description: Total number of temp blocks read by the statement
      usage: COUNTER
    - temp_blks_written:
      description: Total number of temp blocks written by the statement
      usage: COUNTER
    - blk_read_time:
      description: >-
        Total time the statement spent reading blocks, in milliseconds (if
        track_io_timing is enabled, otherwise zero)
      usage: GAUGE
    - blk_write_time:
      description: >-
        Total time the statement spent writing blocks, in milliseconds (if
        track_io_timing is enabled, otherwise zero)
      usage: GAUGE
  query: >-
      SELECT
      r.rolname,
      d.datname,
      queryid,
      query,
      calls,
      total_time,
      min_time,
      max_time,
      mean_time,
      stddev_time,
      rows,
      shared_blks_hit,
      shared_blks_read,
      shared_blks_dirtied,
      shared_blks_written,
      local_blks_hit,
      local_blks_read,
      local_blks_dirtied,
      local_blks_written,
      temp_blks_read,
      temp_blks_written,
      blk_read_time,
      blk_write_time
      FROM pg_stat_statements s
      LEFT JOIN pg_roles r on (s.userid = r.oid)
      LEFT JOIN pg_database d on (s.dbid = d.oid)
