---
# {{ ansible_managed }}

# These stats may not be available
pg_statio_user_tables:
  metrics:
    - schemaname:
      description: Name of the schema that this table is in
      usage: LABEL
    - relname:
      description: Name of this table
      usage: LABEL
    - heap_blks_read:
      description: Number of disk blocks read from this table
      usage: COUNTER
    - heap_blks_hit:
      description: Number of buffer hits in this table
      usage: COUNTER
    - idx_blks_read:
      description: Number of disk blocks read from all indexes on this table
      usage: COUNTER
    - idx_blks_hit:
      description: Number of buffer hits in all indexes on this table
      usage: COUNTER
    - toast_blks_read:
      description: >-
        Number of disk blocks read from this table's TOAST table (if any)
      usage: COUNTER
    - toast_blks_hit:
      description: Number of buffer hits in this table's TOAST table (if any)
      usage: COUNTER
    - tidx_blks_read:
      description: >-
        Number of disk blocks read from this table's TOAST table index (if any)
      usage: COUNTER
    - tidx_blks_hit:
      description: >-
        Number of buffer hits in this table's TOAST table index (if any)
      usage: COUNTER
  query: >-
    SELECT schemaname, relname, heap_blks_read, heap_blks_hit, idx_blks_read,
    idx_blks_hit, toast_blks_read, toast_blks_hit, tidx_blks_read,
    tidx_blks_hit FROM pg_statio_user_tables
