---
# GCS Bucket (Backups)
- name: "GCP: Create bucket '{{ gcp_bucket_name }}'"
  google.cloud.gcp_storage_bucket:
    auth_kind: "serviceaccount"
    service_account_contents: "{{ gcp_service_account_contents }}"
    project: "{{ gcp_project | default(project_info.resources[0].projectNumber) }}"
    name: "{{ gcp_bucket_name }}"
    storage_class: "{{ gcp_bucket_storage_class }}"
    predefined_default_object_acl: "{{ gcp_bucket_default_object_acl }}"
    state: present
  when:
    - (pgbackrest_install | bool or wal_g_install | bool)
    - gcp_bucket_create | bool
