---
# Extension Auto-Setup: repository

# TimescaleDB (if 'enable_timescale' is 'true')
- block:
    # Debian based
    - name: Add TimescaleDB repository
      ansible.builtin.deb822_repository:
        name: "timescaledb"
        types: [deb]
        uris: "https://packagecloud.io/timescale/timescaledb/{{ ansible_distribution | lower }}" # amd64 and arm64 are supported
        signed_by: "https://packagecloud.io/timescale/timescaledb/gpgkey"
        suites: "{{ ansible_distribution_release }}"
        components: [main]
        state: present
        enabled: true
      when: ansible_os_family == "Debian"

    # RedHat based
    - name: Add TimescaleDB repository
      ansible.builtin.yum_repository:
        name: "timescaledb"
        description: "TimescaleDB Repository"
        baseurl: "https://packagecloud.io/timescale/timescaledb/el/{{ ansible_distribution_major_version }}/x86_64" # no arm64 support
        gpgkey: "https://packagecloud.io/timescale/timescaledb/gpgkey"
        gpgcheck: "no"
      when: ansible_os_family == "RedHat" and ansible_architecture in ["x86_64", "amd64"]
  environment: "{{ proxy_env | default({}) }}"
  when: (enable_timescale | default(false) | bool) or (enable_timescaledb | default(false) | bool)
  tags: add_repo, timescaledb, timescale

# Citus (if 'enable_citus' is 'true')
- block:
    # Debian based
    - name: Add Citus repository
      ansible.builtin.deb822_repository:
        name: "citusdata"
        types: [deb]
        uris: "https://repos.citusdata.com/community/{{ ansible_distribution | lower }}/" # no arm64 support (TODO)
        suites: "{{ ansible_distribution_release }}"
        components: [main]
        signed_by: "https://repos.citusdata.com/community/gpgkey"
        state: present
        enabled: true
      when: ansible_os_family == "Debian" and ansible_architecture in ["x86_64", "amd64"]

    # RedHat based
    # TODO: Tests have shown that distributions such as Rocky Linux, AlmaLinux, Oracle Linux, and CentOS Stream are not yet supported.
  #    - name: Add Citus repository
  #      ansible.builtin.yum_repository:
  #        name: "citusdata"
  #        description: "Citus Repository"
  #        baseurl: "https://repos.citusdata.com/community/yum/{{ ansible_distribution_major_version }}/x86_64"
  #        gpgkey: "https://repos.citusdata.com/community/gpgkey"
  #        gpgcheck: "no"
  #      when: ansible_os_family == "RedHat"
  environment: "{{ proxy_env | default({}) }}"
  when:
    - enable_citus | default(false) | bool
    - postgresql_version | int >= 11
  tags: add_repo, citus
