import { PROVIDERS } from '@shared/config/constants.ts';

import { SECRET_MODAL_CONTENT_FORM_FIELD_NAMES } from '@entities/secret-form-block/model/constants.ts';

export const CLUSTER_SECRET_MODAL_FORM_FIELD_NAMES = Object.freeze({
  ...SECRET_MODAL_CONTENT_FORM_FIELD_NAMES,
  IS_SAVE_TO_CONSOLE: 'isSaveToConsole',
});

export const PROVIDER_CODE_TO_ANSIBLE_USER_MAP = Object.freeze({
  [PROVIDERS.AWS]: 'ubuntu',
  [PROVIDERS.GCP]: 'root',
  [PROVIDERS.AZURE]: 'azureadmin',
  [PROVIDERS.DIGITAL_OCEAN]: 'root',
  [PROVIDERS.HETZNER]: 'root',
});

export const CLUSTER_SECRET_MODAL_FORM_DEFAULT_VALUES = Object.freeze({
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.SECRET_TYPE]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.SECRET_NAME]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.AWS_ACCESS_KEY_ID]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.AWS_SECRET_ACCESS_KEY]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.GCP_SERVICE_ACCOUNT_CONTENTS]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.DO_API_TOKEN]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.AZURE_SUBSCRIPTION_ID]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.AZURE_CLIENT_ID]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.AZURE_SECRET]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.AZURE_TENANT]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.HCLOUD_API_TOKEN]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.SSH_PRIVATE_KEY]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.USERNAME]: '',
  [SECRET_MODAL_CONTENT_FORM_FIELD_NAMES.PASSWORD]: '',
});
