---
- name: "Edit patroni.yml | disable noloadbalance, nosync, nofailover"
  ansible.builtin.replace:
    path: /etc/patroni/patroni.yml
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: "noloadbalance: true", replace: "noloadbalance: false" }
    - { regexp: "nosync: true", replace: "nosync: false" }
    - { regexp: "nofailover: true", replace: "nofailover: false" }
  loop_control:
    label: "{{ item.replace }}"

- name: Reload patroni service
  ansible.builtin.systemd:
    daemon_reload: true
    name: patroni
    enabled: true
    state: reloaded

- name: Make sure replica endpoint is available
  ansible.builtin.uri:
    url: http://{{ patroni_bind_address | default(bind_address, true) }}:{{ patroni_restapi_port }}/replica
    status_code: 200
  register: patroni_replica_result
  until: patroni_replica_result.status == 200
  retries: 30
  delay: 2
  environment:
    no_proxy: "{{ patroni_bind_address | default(bind_address, true) }}"

# Warming up caches after reboot (is 'reboot_host_post_delay' is defined)
- name: "Wait {{ reboot_host_post_delay }} minutes for caches to warm up after reboot"
  ansible.builtin.pause:
    minutes: "{{ reboot_host_post_delay }}"
  when:
    - (reboot_result.rebooted is defined and reboot_result.rebooted)
    - (reboot_host_post_delay is defined and reboot_host_post_delay | int > 0)
    - (inventory_hostname in groups['secondary'] and groups['secondary'] | length > 1)
