---
# File: tls.yml - TLS tasks for Consul

# Enables TLS encryption with a self-signed certificate if 'tls_cert_generate' is 'true'.
- block:
    - name: Generate Consul TLS certificate
      ansible.builtin.include_role:
        name: vitabaks.autobase.tls_certificate
      vars:
        generate_tls_owner: "{{ consul_user }}"
        generate_tls_common_name: "{{ consul_tls_common_name | default('Consul') }}"
        generate_tls_dir: "{{ consul_tls_dir | default('/etc/consul/tls') }}"
        tls_group_name: "consul_instances"
        tls_cert_regenerate: "{{ consul_tls_cert_regenerate | default(cluster_scaling|d(false)) }}"  # Regenerate when adding nodes

    - name: Copy Consul TLS certificate, key and CA to all nodes
      ansible.builtin.include_role:
        name: vitabaks.autobase.tls_certificate
        tasks_from: copy
      vars:
        tls_group_name: "consul_instances"
        fetch_tls_dir: "{{ consul_tls_dir | default('/etc/consul/tls') }}"
        copy_tls_dir: "{{ consul_tls_dir | default('/etc/consul/tls') }}"
        copy_tls_owner: "{{ consul_user }}"
  when: tls_cert_generate | default(false) | bool

# Copy the existing TLS certificates from the role's files directory if 'tls_cert_generate' is 'false'.
- block:
    - name: Create SSL directory
      ansible.builtin.file:
        dest: "{{ consul_tls_dir }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: "0755"

    - name: Copy CA certificate
      ansible.builtin.copy:
        remote_src: "{{ consul_tls_files_remote_src }}"
        src: "{{ consul_tls_ca_crt }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_ca_crt | basename }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: "0644"
      notify: restart consul

  when:
    - not tls_cert_generate | default(false) | bool
    - consul_tls_copy_keys | bool

- block:
    - name: Copy server certificate
      ansible.builtin.copy:
        remote_src: "{{ consul_tls_files_remote_src }}"
        src: "{{ consul_tls_server_crt }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_server_crt | basename }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: "0644"
      notify: restart consul

    - name: Copy server key
      ansible.builtin.copy:
        remote_src: "{{ consul_tls_files_remote_src }}"
        src: "{{ consul_tls_server_key }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_server_key | basename }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: "0600"
      notify: restart consul

  when:
    - not tls_cert_generate | default(false) | bool
    - consul_tls_copy_keys | bool
    - auto_encrypt is not defined or (auto_encrypt is defined and not auto_encrypt.enabled | bool) or (consul_node_role != 'client') | bool
