---
- name: Perform failover of the Patroni leader role to the selected replica
  become: true
  become_user: postgres
  ansible.builtin.command: >-
    patronictl -c /etc/patroni/patroni.yml failover {{ patroni_cluster_name }}
    --candidate {{ patroni_failover_candidate_name | default(ansible_hostname, true) }} --force
  environment:
    PATH: "{{ ansible_env.PATH | default('') }}:/usr/bin:/usr/local/bin"

- name: Make sure that the selected Patroni replica is now the leader
  ansible.builtin.uri:
    url: >-
      {{ patroni_restapi_protocol | default('https') }}://{{ patroni_restapi_connect_addr
        | default(patroni_bind_address | default(bind_address, true), true) }}:{{ patroni_restapi_port
        | default('8008') }}/leader
    status_code: 200
    ca_path: "{{ patroni_restapi_cafile | default(omit, true) }}"
  register: patroni_failover_leader_result
  changed_when: false
  check_mode: false
  until: patroni_failover_leader_result.status == 200
  retries: 300
  delay: 2
  environment:
    no_proxy: "{{ patroni_bind_address | default(bind_address, true) }}"
