---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.packages is not defined
  check_mode: false

- name: Install keepalived packages
  ansible.builtin.package:
    name: keepalived
  register: package_status
  until: package_status is success
  delay: 5
  retries: 3
  environment: "{{ proxy_env | default({}) }}"
  when: "'keepalived' not in ansible_facts.packages"
  tags: keepalived_install, keepalived

- name: Make sure the kernel parameters "net.ipv4.ip_nonlocal_bind", "net.ipv4.ip_forward" are enabled
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: true
    state: present
    reload: true
  loop:
    - "net.ipv4.ip_nonlocal_bind"
    - "net.ipv4.ip_forward"
  tags: keepalived_conf, keepalived

- name: Make sure the "/usr/libexec/keepalived" directory exists
  ansible.builtin.file:
    dest: /usr/libexec/keepalived
    state: directory
    owner: root
    group: root
    mode: "0750"
  tags: keepalived_conf, keepalived

- name: Create vrrp_script "/usr/libexec/keepalived/haproxy_check.sh"
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      /bin/kill -0 `cat /run/haproxy/haproxy.pid`
    dest: /usr/libexec/keepalived/haproxy_check.sh
    owner: root
    group: root
    mode: "0700"
  notify: "restart keepalived"
  tags: keepalived_conf, keepalived

- name: Generate conf file "/etc/keepalived/keepalived.conf"
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify: "restart keepalived"
  when: add_balancer is not defined or not add_balancer|bool
  tags: keepalived_conf, keepalived

- block: # for add_balancer.yml
    - name: "Fetch keepalived.conf conf file from {{ inventory_hostname }}"
      run_once: true
      ansible.builtin.fetch:
        src: /etc/keepalived/keepalived.conf
        dest: "{{ files_dir | default(playbook_dir ~ '/files') }}/keepalived.conf"
        validate_checksum: true
        flat: true
      when: "'balancers' in group_names"

    - name: Copy keepalived.conf conf file to replica
      ansible.builtin.copy:
        src: "{{ files_dir | default(playbook_dir ~ '/files') }}/keepalived.conf"
        dest: /etc/keepalived/keepalived.conf
      notify: "restart keepalived"

    - name: Remove keepalived.conf file from localhost
      become: false
      run_once: true
      ansible.builtin.file:
        path: "{{ files_dir | default(playbook_dir ~ '/files') }}/keepalived.conf"
        state: absent
      delegate_to: localhost

    - name: Prepare keepalived.conf conf file (replace "interface")
      ansible.builtin.lineinfile:
        path: /etc/keepalived/keepalived.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: true
      loop:
        - { regexp: "^.*interface", line: "   interface {{ vip_interface }}" }
      loop_control:
        label: "{{ item.line }}"
      notify: "restart keepalived"
  when: add_balancer is defined and add_balancer|bool
  tags: keepalived_conf, keepalived

- name: Selinux | Change the keepalived_t domain to permissive
  community.general.selinux_permissive:
    name: keepalived_t
    permissive: true
  when: ansible_selinux.status is defined and
    ansible_selinux.status == 'enabled'
  ignore_errors: true # noqa ignore-errors
  tags: keepalived, keepalived_selinux
