---
- name: Add extensions to the databases
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    name: "{{ item.ext }}"
    schema: "{{ item.schema | default('public') }}"
    login_db: "{{ item.db }}"
    login_host: "127.0.0.1"
    login_port: "{{ postgresql_port }}"
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"
    state: present
  ignore_errors: true
  loop: "{{ postgresql_extensions | flatten(1) }}"
  when:
    - postgresql_extensions is defined
    - postgresql_extensions | length > 0
  tags: postgresql_extensions
