---
- block:
    - name: Download Netdata installation script
      ansible.builtin.get_url:
        url: "{{ netdata_kickstart_url | default('https://get.netdata.cloud/kickstart.sh') }}"
        dest: /tmp/netdata-kickstart.sh
        mode: +x
      register: get_url_status
      until: get_url_status is success
      delay: 10
      retries: 3

    - name: Install Netdata
      ansible.builtin.command: /tmp/netdata-kickstart.sh {{ netdata_install_options | default('--dont-wait') }}
      register: install_status
      until: install_status is success
      delay: 10
      retries: 3

    - name: Configure Netdata
      ansible.builtin.template:
        src: templates/netdata.conf.j2
        dest: /etc/netdata/netdata.conf
        owner: root
        group: root
        mode: u=wrx,g=rx,o=r,+x

    - name: Restart Netdata
      ansible.builtin.service:
        name: netdata
        state: restarted
  environment: "{{ proxy_env | default({}) }}"
  ignore_errors: "{{ netdata_install_ignore_errors | default(true) }}" # show the error and continue the playbook execution
  when: netdata_install | default(false)| bool
  tags: netdata
