---
- name: Make sure the PostgreSQL schemas are present
  become: true
  become_user: postgres
  community.postgresql.postgresql_schema:
    name: "{{ item.schema }}"
    owner: "{{ item.owner }}"
    login_db: "{{ item.db }}"
    login_unix_socket: "{{ postgresql_unix_socket_dir }}"
    login_port: "{{ postgresql_port }}"
    state: present
  ignore_errors: true
  loop: "{{ postgresql_schemas | flatten(1) }}"
  when:
    - postgresql_schemas | default('') | length > 0
    - patroni_standby_cluster.host | default('') | length < 1 # do not perform on the Standby Cluster
  tags: postgresql_schemas
