---
- name: vitabaks.autobase.add_balancer | Add HAProxy balancer node
  hosts: balancers
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  pre_tasks:
    - name: "[Pre-Check] Check if there is a node with new_node set to true"
      ansible.builtin.set_fact:
        new_nodes: "{{ new_nodes | default([]) + [item] }}"
      when: hostvars[item]['new_node'] | default(false) | bool
      loop: "{{ groups['balancers'] }}"
      tags: always

    # Stop, if no nodes found with new_node variable
    - name: "Pre-Check error. No nodes found with new_node set to true"
      run_once: true # noqa run-once
      ansible.builtin.fail:
        msg: "Please specify the new_node=true variable for the new balancer server to add it to the existing cluster."
      when: new_nodes | default([]) | length < 1

    - name: Print a list of new balancer nodes
      run_once: true # noqa run-once
      ansible.builtin.debug:
        var: new_nodes
      tags: always

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      when:
        - new_node | default(false) | bool
        - ansible_os_family == "Debian"
        - installation_method | default('packages') == "packages"

    - name: Make sure the gnupg and apt-transport-https packages are present
      ansible.builtin.apt:
        pkg:
          - gnupg
          - apt-transport-https
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      when:
        - new_node | default(false) | bool
        - ansible_os_family == "Debian"
        - installation_method | default('packages') == "packages"

    - name: Build a firewall_ports_dynamic_var
      ansible.builtin.set_fact:
        firewall_ports_dynamic_var: "{{ firewall_ports_dynamic_var | default([]) + (firewall_allowed_tcp_ports_for[item] | default([])) }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when:
        - new_node | default(false) | bool
        - firewall_enabled_at_boot | default(false)| bool
      tags: firewall

    - name: Build a firewall_rules_dynamic_var
      ansible.builtin.set_fact:
        firewall_rules_dynamic_var: "{{ firewall_rules_dynamic_var | default([]) + (firewall_additional_rules_for[item] | default([])) }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when:
        - new_node | default(false) | bool
        - firewall_enabled_at_boot | default(false)| bool
      tags: firewall

  roles:
    - role: vitabaks.autobase.firewall
      environment: "{{ proxy_env | default({}) }}"
      vars:
        firewall_allowed_tcp_ports: "{{ firewall_ports_dynamic_var | default([]) | unique }}"
        firewall_additional_rules: "{{ firewall_rules_dynamic_var | default([]) | unique }}"
      when:
        - new_node | default(false) | bool
        - firewall_enabled_at_boot | default(false)| bool
      tags: firewall

    - role: vitabaks.autobase.sysctl
      when:
        - new_node | default(false) | bool

  tasks:
    - name: Add host to group new_balancer (in-memory inventory)
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: new_balancer
      loop: "{{ new_nodes }}"
      changed_when: false
      tags: always

- name: vitabaks.autobase.add_balancer | Add load balancer
  hosts: new_balancer
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars:
    add_balancer: true

  roles:
    - role: vitabaks.autobase.hostname
    - role: vitabaks.autobase.resolv_conf

    - role: vitabaks.autobase.haproxy
      when: with_haproxy_load_balancing | default(false) | bool

    - role: vitabaks.autobase.confd
      when: dcs_type | default('etcd') == "etcd" and
        with_haproxy_load_balancing | default(false) | bool

    - role: vitabaks.autobase.keepalived
      when: cluster_vip is defined and cluster_vip | length > 0 and
        with_haproxy_load_balancing | default(false) | bool
