---
- name: vitabaks.autobase.add_pgnode | PostgreSQL HA Cluster Scaling (add a replica node)
  hosts: postgres_cluster
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  pre_tasks:
    - name: Set maintenance variable
      ansible.builtin.set_fact:
        postgresql_cluster_maintenance: true

    - name: "[Pre-Check] Check if there is a node with new_node set to true"
      ansible.builtin.set_fact:
        new_nodes: "{{ new_nodes | default([]) + [item] }}"
      loop: "{{ groups['replica'] | default([]) }}"
      when:
        - "'replica' in groups and groups['replica'] | length > 0"
        - hostvars[item]['new_node'] | default(false) | bool
      tags: always

    # Stop, if no nodes found with new_node variable
    - name: "Pre-Check error. No nodes found with new_node set to true"
      run_once: true # noqa run-once
      ansible.builtin.fail:
        msg: "Please specify the new_node=true variable for the new server to add it to the existing cluster."
      when: new_nodes | default([]) | length < 1
      tags: always

    - name: Print a list of new nodes
      run_once: true # noqa run-once
      ansible.builtin.debug:
        var: new_nodes
      tags: always

    - name: Add a new node to pg_hba.conf on existing cluster nodes
      ansible.builtin.include_role:
        name: vitabaks.autobase.patroni
        tasks_from: pg_hba
      when: not new_node | default(false) | bool

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      when:
        - new_node | default(false) | bool
        - ansible_os_family == "Debian"
        - installation_method | default('packages') == "packages"

    - name: Make sure the gnupg and apt-transport-https packages are present
      ansible.builtin.apt:
        pkg:
          - gnupg
          - apt-transport-https
        state: present
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      when:
        - new_node | default(false) | bool
        - ansible_os_family == "Debian"
        - installation_method | default('packages') == "packages"

    - name: Build a firewall_ports_dynamic_var
      ansible.builtin.set_fact:
        firewall_ports_dynamic_var: "{{ firewall_ports_dynamic_var | default([]) + (firewall_allowed_tcp_ports_for[item] | default([])) }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when:
        - new_node | default(false) | bool
        - firewall_enabled_at_boot | default(false)| bool
      tags: firewall

    - name: Build a firewall_rules_dynamic_var
      ansible.builtin.set_fact:
        firewall_rules_dynamic_var: "{{ firewall_rules_dynamic_var | default([]) + (firewall_additional_rules_for[item] | default([])) }}"
      loop: "{{ hostvars[inventory_hostname].group_names }}"
      when:
        - new_node | default(false) | bool
        - firewall_enabled_at_boot | default(false)| bool
      tags: firewall

  roles:
    - role: vitabaks.autobase.firewall
      environment: "{{ proxy_env | default({}) }}"
      vars:
        firewall_allowed_tcp_ports: "{{ firewall_ports_dynamic_var | default([]) | unique }}"
        firewall_additional_rules: "{{ firewall_rules_dynamic_var | default([]) | unique }}"
      when:
        - new_node | default(false) | bool
        - firewall_enabled_at_boot | default(false)| bool
      tags: firewall

    - role: vitabaks.autobase.pre_checks
      vars:
        minimal_ansible_version: 2.16.0
        timescale_minimal_pg_version: 12 # if enable_timescale is defined
      tags: always

    - role: vitabaks.autobase.sysctl
      when:
        - new_node | default(false) | bool

    - role: vitabaks.autobase.ssh_keys
      when:
        - enable_ssh_key_based_authentication | default(false) | bool

  tasks:
    - name: Add host to group new_replica (in-memory inventory)
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: new_replica
      loop: "{{ new_nodes }}"
      changed_when: false
      tags: always

- name: vitabaks.autobase.add_pgnode | Configure new PostgreSQL node
  hosts: new_replica
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    # if 'dcs_type' is 'consul'
    - name: Add a nameserver entry poining to localhost for dnsmasq
      ansible.builtin.set_fact:
        nameservers: "{{ ['127.0.0.1'] + (nameservers | default([])) }}"
      when: dcs_type | default('etcd') == "consul" and consul_dnsmasq_enable | default(true) | bool and ('127.0.0.1' not in (nameservers | default([])))

  roles:
    - role: vitabaks.autobase.hostname
    - role: vitabaks.autobase.resolv_conf
    - role: vitabaks.autobase.etc_hosts
    - role: vitabaks.autobase.add_repository
    - role: vitabaks.autobase.packages
    - role: vitabaks.autobase.sudo
    - role: vitabaks.autobase.swap
    - role: vitabaks.autobase.transparent_huge_pages
    - role: vitabaks.autobase.pam_limits
    - role: vitabaks.autobase.io_scheduler
    - role: vitabaks.autobase.locales
    - role: vitabaks.autobase.timezone
    - role: vitabaks.autobase.ntp
    - role: vitabaks.autobase.copy
    - role: vitabaks.autobase.cron

- name: vitabaks.autobase.add_pgnode | Configure pgBackRest
  hosts: pgbackrest:postgres_cluster
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: vitabaks.autobase.pgbackrest
      when: pgbackrest_install|bool

- name: vitabaks.autobase.add_pgnode | Import Consul playbook
  ansible.builtin.import_playbook: consul_cluster.yml
  when: dcs_type | default('etcd') == "consul"
  tags: consul

- name: vitabaks.autobase.add_pgnode | Add new PostgreSQL replica to the cluster
  hosts: new_replica
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  vars:
    existing_pgcluster: true

  pre_tasks:
    - name: Copy certificates
      ansible.builtin.include_role:
        name: vitabaks.autobase.tls_certificate
        tasks_from: copy
      when: tls_cert_generate | default(true) | bool

  roles:
    - role: vitabaks.autobase.wal_g
      when: wal_g_install | default(false) | bool

    - role: vitabaks.autobase.pg_probackup
      when: pg_probackup_install | default(false) | bool

    - role: vitabaks.autobase.pgbouncer
      when: pgbouncer_install | default(false) | bool

    - role: vitabaks.autobase.pgpass

    - role: vitabaks.autobase.patroni

    - role: vitabaks.autobase.vip_manager
      when: not with_haproxy_load_balancing | default(false) | bool and
        (cluster_vip is defined and cluster_vip | length > 0)

    - role: vitabaks.autobase.netdata

    # finish (info)
    - role: vitabaks.autobase.deploy_finish
