---
- name: vitabaks.autobase.remove_cluster | Remove PostgreSQL HA Cluster
  hosts: postgres_cluster
  become: true
  pre_tasks:
    - name: Load common variables
      ansible.builtin.include_role:
        name: vitabaks.autobase.common
  tasks:
    - block:
        - name: Stop and disable patroni service
          ansible.builtin.service:
            name: patroni
            state: stopped
            enabled: false

        - name: Delete PostgreSQL content
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ postgresql_data_dir }}"
            - "{{ postgresql_conf_dir }}"
      ignore_errors: true
      when: remove_postgres | default(false) | bool

    - block:
        - name: Delete PgBackRest repository
          ansible.builtin.file:
            # path: pgbackrest_conf global repo1-path
            path: /var/lib/pgbackrest
            state: absent

        - name: Delete PgBackRest cron
          ansible.builtin.file:
            path: /etc/cron.d/pgbackrest
            state: absent
      ignore_errors: true
      when: remove_pgbackrest | default(false) | bool

- name: vitabaks.autobase.remove_cluster | Consul Cluster Play
  hosts: consul_instances
  become: true
  pre_tasks:
    - name: Load common variables
      ansible.builtin.include_role:
        name: vitabaks.autobase.common
  tasks:
    - block:
        - name: Stop and disable consul service
          ansible.builtin.service:
            name: consul
            state: stopped
            enabled: false

        - name: Delete consul content
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ consul_data_path }}"
            - "{{ consul_config_path }}"
      ignore_errors: true
      when: remove_consul | default(false) | bool

- name: vitabaks.autobase.remove_cluster | Etcd Cluster Play
  hosts: etcd_cluster
  become: true
  pre_tasks:
    - name: Load common variables
      ansible.builtin.include_role:
        name: vitabaks.autobase.common
  tasks:
    - block:
        - name: Stop and disable etcd service
          ansible.builtin.service:
            name: etcd
            state: stopped
            enabled: false

        - name: Delete etcd content
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ etcd_data_dir }}"
            - "{{ etcd_conf_dir }}"
      ignore_errors: true
      when: remove_etcd | default(false) | bool
