---
- name: "Update docker network(s)"
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: "Create docker network: test_docker_network"
      community.docker.docker_network:
        name: test_docker_network
        driver: bridge
        driver_options:
          com.docker.network.driver.mtu: 1440
        enable_ipv6: false
        internal: false
        ipam_config:
          - subnet: 10.172.0.0/24
            gateway: 10.172.0.1
        force: true
        state: present
        labels:
          owner: molecule

    - name: "Install netaddr dependency on controlling host"
      ansible.builtin.pip:
        name: netaddr
      environment:
        PIP_BREAK_SYSTEM_PACKAGES: "1"

    - name: Generate molecule SSH key on control node
      ansible.builtin.user:
        name: "{{ ansible_facts.user }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/molecule_rsa

- name: Prepare instances for Molecule
  hosts: all
  become: true
  become_method: su
  tasks:
    - name: Ensure SSH client package is installed
      ansible.builtin.package:
        name: "{{ ssh_client_package }}"
        state: present
      vars:
        ssh_client_package: "{{ 'openssh-client' if ansible_os_family == 'Debian' else 'openssh-clients' }}"

    - name: Copy public SSH key to molecule instances
      ansible.builtin.copy:
        src: ~/.ssh/molecule_rsa.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0600'

...
