---
# 🚀 This playbook is designed to verify the default Molecule configuration
# 🎯 The objective is to ensure that all tasks and roles are correctly set up and functioning as expected

- name: Molecule.default.verify
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Gather network facts
      ansible.builtin.setup:
        gather_subset:
          - network
      when: ansible_all_ipv4_addresses is not defined

    # Define bind_address for each host (first private IPv4), unless set in inventory.
    - name: Expose bind_address as facts
      ansible.builtin.set_fact:
        bind_address: "{{ ansible_all_ipv4_addresses | ansible.utils.ipaddr('private') | first }}"
      when: bind_address is not defined

  tasks:
    # 📝 Including the common variables for the Molecule default configuration
    # This file contains all the necessary variables for the playbook
    - name: Molecule.default.verify | Include Common Variables
      ansible.builtin.include_vars:
        file: ../../roles/common/defaults/main.yml

    # Including the dcs_type variable redefined in converge.yml
    - name: Molecule.default.verify | Include dcs_type Variable
      ansible.builtin.include_vars:
        file: ../../dcs_type.yml

    # 🔄 Including all tests for the Molecule default configuration
    # These tests ensure that all components of the configuration are functioning correctly
    - name: Molecule.default.verify | Include All Tests
      ansible.builtin.include_tasks: "{{ item }}"
      with_fileglob:
        - ../tests/variables/main.yml
        - ../tests/etcd/*.yml
        - ../tests/patroni/*.yml
        - ../tests/postgres/*.yml
        - ../tests/roles/confd/main.yml
        - ../tests/roles/deploy_finish/main.yml
        - ../tests/roles/haproxy/main.yml
        - ../tests/roles/patroni/main.yml
        - ../tests/roles/pre_checks/main.yml
        - ../tests/roles/swap/main.yml
