---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Update apt cache
      become: true
      become_method: su
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Ensure SSH client package is installed
      become: true
      become_method: su
      ansible.builtin.package:
        name: "{{ ssh_client_package }}"
        state: present
      vars:
        ssh_client_package: "{{ 'openssh-client' if ansible_os_family == 'Debian' else 'openssh-clients' }}"
      when: ansible_distribution != "MacOSX"

    - name: Get system username on control node
      ansible.builtin.command: whoami
      register: control_user
      changed_when: false
      delegate_to: localhost
      run_once: true # noqa run-once

    - name: Generate molecule SSH key on control node
      ansible.builtin.user:
        name: "{{ control_user.stdout }}"
        generate_ssh_key: true
        ssh_key_bits: 2048
        ssh_key_file: /tmp/molecule_rsa
      delegate_to: localhost
      run_once: true # noqa run-once

    - name: Get system username on molecule instances
      ansible.builtin.command: whoami
      register: instance_user
      changed_when: false

    - name: Ensure SSH directory exists on molecule instances
      become: true
      become_method: su
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: '0700'

    - name: Copy public SSH key to molecule instances
      become: true
      become_method: su
      ansible.builtin.copy:
        src: /tmp/molecule_rsa.pub
        dest: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
        owner: "{{ instance_user.stdout }}"
        group: "{{ instance_user.stdout }}"
        mode: '0600'

    - name: Switch to SSH key-based authentication
      ansible.builtin.set_fact:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_private_key_file: /tmp/molecule_rsa

    - name: Set variables for molecule
      ansible.builtin.set_fact:
        firewall_enable_ipv6: false # Added to prevent test failures in CI.
        swap_file_create: false # Added to prevent test failures in CI.
        sysctl_set: false # Added to prevent test failures in CI.
        nameservers: ["8.8.8.8", "9.9.9.9"]
        with_haproxy_load_balancing: true
        cacheable: true

    - name: Update all system packages
      ansible.builtin.include_role:
        name: ../../roles/update
        tasks_from: system

    - name: Include postgrespro vars
      ansible.builtin.include_vars: vars/postgrespro_vars.yml

- name: Deploy PostgreSQL Cluster
  ansible.builtin.import_playbook: ../../deploy_pgcluster.yml
