---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Set variables for molecule
      ansible.builtin.set_fact:
        ansible_become_method: su # Override become_method
        firewall_enable_ipv6: false # Added to prevent test failures in CI.
        swap_file_create: false # Added to prevent test failures in CI.
        sysctl_set: false # Added to prevent test failures in CI.
        nameservers: ["8.8.8.8", "9.9.9.9"]
        with_haproxy_load_balancing: true
        cacheable: true

    - name: Update all system packages
      ansible.builtin.include_role:
        name: ../../roles/update
        tasks_from: system

    - name: Include postgrespro vars
      ansible.builtin.include_vars: vars/postgrespro_vars.yml

- name: Deploy PostgreSQL Cluster
  ansible.builtin.import_playbook: ../../deploy_pgcluster.yml
