---
- name: remove_cluster.yml | Remove PostgreSQL HA Cluster
  hosts: postgres_cluster
  become: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
    - name: Include vault variables
      ansible.builtin.include_vars: "vars/vault.yml"
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
  tasks:
    - block:
        - name: Stop Patroni service
          ansible.builtin.service:
            name: patroni
            state: stopped
            enabled: false
        - name: Delete PostgreSQL database content
          ansible.builtin.file:
            path: "{{ postgresql_data_dir }}"
            state: absent
      when: remove_postgres | default(false) | bool
      ignore_errors: true
    - block:
        - name: Delete PgBackRest repository
          ansible.builtin.file:
            # path: pgbackrest_conf global repo1-path
            path: /var/lib/pgbackrest
            state: absent
        - name: Delete PgBackRest cron
          ansible.builtin.file:
            path: /etc/cron.d/pgbackrest
            state: absent
      when: pgbackrest_install | default(false) | bool
      ignore_errors: true

- name: remove_cluster.yml | Consul Cluster Play
  hosts: consul_instances
  become: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
    - name: Include vault variables
      ansible.builtin.include_vars: "vars/vault.yml"
  tasks:
    - block:
        - name: Stop Consul service
          ansible.builtin.service:
            name: consul
            state: stopped
            enabled: false
        - name: Delete Consul content
          ansible.builtin.file:
            path: "{{ consul_data_path }}"
            state: absent
        - name: Delete Consul serivce
          ansible.builtin.file:
            path: /lib/systemd/system/consul.service
            state: absent
      when: remove_consul | default(false) | bool
      ignore_errors: true

- name: remove_cluster.yml | Etcd Cluster Play
  hosts: etcd_cluster
  become: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
    - name: Include vault variables
      ansible.builtin.include_vars: "vars/vault.yml"
  tasks:
    - block:
        - name: Stop Etcd service
          ansible.builtin.service:
            name: etcd
            state: stopped
            enabled: false
        - name: Delete Etcd content
          ansible.builtin.file:
            path: "{{ etcd_data_dir }}/member"
            state: absent
      when: remove_etcd | default(false) | bool
      ignore_errors: true
