---
collections:
  - name: amazon.aws
    version: "==9.1.1"
  - name: google.cloud
    version: "==1.5.1"
  - name: azure.azcollection
    version: "==3.1.0"
  - name: community.digitalocean
    version: "==1.27.0"
  - name: hetzner.hcloud
    version: "==4.2.2"
  - name: community.postgresql
    version: "==3.10.2"
  - name: community.docker
    version: "==4.3.1"
  - name: community.general
    version: "==10.3.0"
