---
collections:
  - name: amazon.aws
    version: ">=10.1.2"
  - name: community.aws
    version: ">=10.0.0"
  - name: google.cloud
    version: ">=1.10.2"
  - name: azure.azcollection
    version: ">=3.10.1"
  - name: community.digitalocean
    version: ">=1.27.0"
  - name: hetzner.hcloud
    version: ">=5.4.0"
  - name: community.postgresql
    version: ">=4.1.0"
  - name: community.docker
    version: ">=4.8.2"
  - name: community.general
    version: ">=11.4.1"
  - name: ansible.posix
    version: ">=2.1.0"
  - name: ansible.utils
    version: ">=6.0.0"
