---
collections:
  - name: amazon.aws
    version: "==9.1.0"
  - name: google.cloud
    version: "==1.4.1"
  - name: azure.azcollection
    version: "==3.1.0"
  - name: community.digitalocean
    version: "==1.27.0"
  - name: hetzner.hcloud
    version: "==4.2.2"
