---
collections:
  - name: amazon.aws
    version: ">=10.1.0"
  - name: community.aws
    version: ">=10.0.0"
  - name: google.cloud
    version: ">=1.7.0"
  - name: azure.azcollection
    version: ">=3.7.0"
  - name: community.digitalocean
    version: ">=1.27.0"
  - name: hetzner.hcloud
    version: ">=5.2.0"
  - name: community.postgresql
    version: ">=3.14.2"
  - name: community.docker
    version: ">=4.6.1"
  - name: community.general
    version: ">=10.7.2"
  - name: ansible.posix
    version: ">=1.6.2"
  - name: ansible.utils
    version: ">=5.1.2"
