---
collections:
  - name: amazon.aws
    version: ">=10.3.1"
  - name: community.aws
    version: ">=10.1.0"
  - name: google.cloud
    version: ">=1.13.0"
  - name: azure.azcollection
    version: ">=3.18.0"
  - name: community.digitalocean
    version: ">=1.27.0"
  - name: hetzner.hcloud
    version: ">=6.9.0"
  - name: community.postgresql
    version: ">=4.2.0"
  - name: community.docker
    version: ">=5.2.0"
  - name: community.general
    version: ">=12.6.1"
  - name: ansible.posix
    version: ">=2.2.0"
  - name: ansible.utils
    version: ">=6.0.2"
