---

- name: Make sure new PostgreSQL data directory "{{ pg_new_datadir }}" exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ pg_new_datadir }}"
    state: directory
    mode: "0700"
    group: postgres
    owner: postgres

- name: Make sure new PostgreSQL data directory "{{ pg_new_datadir }}" is not initialized
  ansible.builtin.stat:
    path: "{{ pg_new_datadir }}/PG_VERSION"
  register: pgdata_initialized

- block:  # if already initialized
    - name: Perform pg_dropcluster
      ansible.builtin.command: >
        /usr/bin/pg_dropcluster --stop {{ pg_new_version }} {{ postgresql_cluster_name }}
      failed_when: false
      when:
        - ansible_os_family == "Debian"
        - pg_new_confdir != pg_new_datadir

    - name: Clear the new PostgreSQL data directory "{{ pg_new_datadir }}"
      ansible.builtin.file:
        path: "{{ pg_new_datadir }}"
        state: "{{ item }}"
        mode: "0700"
        group: postgres
        owner: postgres
      loop:
        - absent
        - directory
  when:
    - pgdata_initialized.stat.exists is defined
    - pgdata_initialized.stat.exists

- name: Get the current install user
  ansible.builtin.command: >-
    {{ pg_old_bindir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc
    "select rolname from pg_roles where oid = 10"
  changed_when: false
  register: pg_install_user
  when:
    - inventory_hostname in groups['primary']

- name: Get the current encodig and data_checksums settings
  ansible.builtin.command: >-
    {{ pg_old_bindir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc "
    select row_to_json(pg_settings)
    from (
      select
        (select datcollate from pg_database where datname = current_database()) as lc_collate,
        (select datctype from pg_database where datname = current_database()) as lc_ctype,
        current_setting('lc_messages') as lc_messages,
        current_setting('lc_monetary') as lc_monetary,
        current_setting('lc_numeric') as lc_numeric,
        current_setting('lc_time') as lc_time,
        current_setting('server_encoding') as server_encoding,
        current_setting('data_checksums') as data_checksums
    ) pg_settings"
  changed_when: false
  register: pg_settings
  when:
    - inventory_hostname in groups['primary']

# for Debian based use pg_createcluster, if the PostgreSQL configuration is not located in the data directory.
# Note: Patroni failure is possible if the default postgresql config files are missing in the /etc/postgresql/...
- name: Initialize new PostgreSQL data directory with default config files
  ansible.builtin.command: >
    /usr/bin/pg_createcluster {{ pg_new_version }} {{ postgresql_cluster_name }}
    --user={{ hostvars[groups['primary'][0]].pg_install_user.stdout }}
    --datadir={{ pg_new_datadir }}
    --encoding={{ (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).server_encoding }}
    --lc-collate={{ (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).lc_collate }}
    --lc-ctype={{ (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).lc_ctype }}
    --lc-messages={{ (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).lc_messages }}
    --lc-monetary={{ (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).lc_monetary }}
    --lc-numeric={{ (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).lc_numeric }}
    --lc-time={{ (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).lc_time }}
    --start-conf=manual
    {% if (hostvars[groups['primary'][0]].pg_settings.stdout | from_json).data_checksums == 'on' %}
    -- --data-checksums
    {% endif %}
  when:
    - ansible_os_family == "Debian"
    - pg_new_confdir != pg_new_datadir

# Use initdb, if the PostgreSQL configuration is located in the data directory.
- name: Initialize new PostgreSQL data directory on the Primary
  ansible.builtin.command: >
    {{ pg_new_bindir }}/initdb
    --username={{ pg_install_user.stdout }}
    --pgdata={{ pg_new_datadir }}
    --encoding={{ (pg_settings.stdout | from_json).server_encoding }}
    --lc-collate={{ (pg_settings.stdout | from_json).lc_collate }}
    --lc-ctype={{ (pg_settings.stdout | from_json).lc_ctype }}
    --lc-messages={{ (pg_settings.stdout | from_json).lc_messages }}
    --lc-monetary={{ (pg_settings.stdout | from_json).lc_monetary }}
    --lc-numeric={{ (pg_settings.stdout | from_json).lc_numeric }}
    --lc-time={{ (pg_settings.stdout | from_json).lc_time }}
    {% if (pg_settings.stdout | from_json).data_checksums == 'on' %}
    --data-checksums
    {% endif %}
  when:
    - inventory_hostname in groups['primary']
    - pg_new_confdir == pg_new_datadir

...
