---
# Prepare the parameters for Patroni.

- name: "Backup the patroni.yml configuration file"
  ansible.builtin.copy:
    src: "{{ patroni_config_file }}"
    dest: "{{ patroni_config_file }}.bkp"
    remote_src: true

- name: Remove patroni.dynamic.json file
  ansible.builtin.file:
    path: "{{ pg_old_datadir }}/patroni.dynamic.json"
    state: absent

# Update the directory path to a new version of PostgresSQL
- name: "Edit patroni.yml | update parameters: data_dir, bin_dir, config_dir"
  ansible.builtin.replace:
    path: "{{ patroni_config_file }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: 'data_dir: {{ pg_old_datadir }}', replace: 'data_dir: {{ pg_new_datadir }}' }
    - { regexp: 'bin_dir: {{ pg_old_bindir }}', replace: 'bin_dir: {{ pg_new_bindir }}' }
    - { regexp: 'config_dir: {{ pg_old_confdir }}', replace: 'config_dir: {{ pg_new_confdir }}' }
  loop_control:
    label: '{{ item.replace }}'

# Prepare the parameters for PostgreSQL (removed or renamed parameters).

- block:  # replacement_sort_tuples (removed in the PG 11)
    # check if the replacement_sort_tuples parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'replacement_sort_tuples' parameter is specified"
      ansible.builtin.command: grep replacement_sort_tuples {{ patroni_config_file }}
      register: replacement_sort_tuples_output
      changed_when: false
      failed_when: false

    # if defined, remove the replacement_sort_tuples parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'replacement_sort_tuples'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)replacement_sort_tuples:.*'
        state: absent
      when: replacement_sort_tuples_output.stdout | length > 0
  when:
    - pg_old_version|int <= 10 and pg_new_version|int >= 11

- block:  # default_with_oids (removed in the PG 12)
    # check if the default_with_oids parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'default_with_oids' parameter is specified"
      ansible.builtin.command: grep default_with_oids {{ patroni_config_file }}
      register: default_with_oids_output
      changed_when: false
      failed_when: false

    # if defined, remove the default_with_oids parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'default_with_oids'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)default_with_oids:.*'
        state: absent
      when: default_with_oids_output.stdout | length > 0
  when:
    - pg_old_version|int <= 11 and pg_new_version|int >= 12

- block:  # wal_keep_segments (removed in the PG 13)
    # check if the wal_keep_segments parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'wal_keep_segments' parameter is specified"
      ansible.builtin.shell: >
        set -o pipefail;
        grep wal_keep_segments {{ patroni_config_file }} | awk '{print $2}' | tail -n 1
      args:
        executable: /bin/bash
      register: wal_keep_segments_output
      changed_when: false
      failed_when: false

    # if defined, replace it to wal_keep_size with a value in MB.
    - name: "Edit patroni.yml | replace parameter: 'wal_keep_segments' to 'wal_keep_size'"
      ansible.builtin.replace:
        path: "{{ patroni_config_file }}"
        regexp: 'wal_keep_segments: ([0-9]+)'
        replace: "wal_keep_size: {{ (wal_keep_segments_output.stdout | int * 16) | string + 'MB' }}"
      when: wal_keep_segments_output.stdout|int > 0
  when:
    - pg_old_version|int <= 12 and pg_new_version|int >= 13

- block:  # operator_precedence_warning (removed in the PG 14)
    # check if the operator_precedence_warning parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'operator_precedence_warning' parameter is specified"
      ansible.builtin.command: grep operator_precedence_warning {{ patroni_config_file }}
      register: operator_precedence_warning_output
      changed_when: false
      failed_when: false

    # if defined, remove the operator_precedence_warning parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'operator_precedence_warning'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)operator_precedence_warning:.*'
        state: absent
      when: operator_precedence_warning_output.stdout | length > 0
  when:
    - pg_old_version|int <= 13 and pg_new_version|int >= 14

- block:  # vacuum_cleanup_index_scale_factor (removed in the PG 14)
    # check if the vacuum_cleanup_index_scale_factor parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'vacuum_cleanup_index_scale_factor' parameter is specified"
      ansible.builtin.command: grep vacuum_cleanup_index_scale_factor {{ patroni_config_file }}
      register: vacuum_cleanup_index_scale_factor_output
      changed_when: false
      failed_when: false

    # if defined, remove the vacuum_cleanup_index_scale_factor parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'vacuum_cleanup_index_scale_factor'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)vacuum_cleanup_index_scale_factor:.*'
        state: absent
      when: vacuum_cleanup_index_scale_factor_output.stdout | length > 0
  when:
    - pg_old_version|int <= 13 and pg_new_version|int >= 14

- block:  # stats_temp_directory (removed in the PG 15)
    # check if the stats_temp_directory parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'stats_temp_directory' parameter is specified"
      ansible.builtin.command: grep stats_temp_directory {{ patroni_config_file }}
      register: stats_temp_directory_output
      changed_when: false
      failed_when: false

    # if defined, remove the stats_temp_directory parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'stats_temp_directory'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)stats_temp_directory:.*'
        state: absent
      when: stats_temp_directory_output.stdout | length > 0
  when:
    - pg_old_version|int <= 14 and pg_new_version|int >= 15

- block:  # force_parallel_mode (removed in the PG 16)
    # check if the force_parallel_mode parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'force_parallel_mode' parameter is specified"
      ansible.builtin.command: grep force_parallel_mode {{ patroni_config_file }}
      register: force_parallel_mode_output
      changed_when: false
      failed_when: false

    # if defined, remove the force_parallel_mode parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'force_parallel_mode'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)force_parallel_mode:.*'
        state: absent
      when: force_parallel_mode_output.stdout | length > 0
  when:
    - pg_old_version|int <= 15 and pg_new_version|int >= 16

- block:  # promote_trigger_file (removed in the PG 16)
    # check if the promote_trigger_file parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'promote_trigger_file' parameter is specified"
      ansible.builtin.command: grep promote_trigger_file {{ patroni_config_file }}
      register: promote_trigger_file_output
      changed_when: false
      failed_when: false

    # if defined, remove the promote_trigger_file parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'promote_trigger_file'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)promote_trigger_file:.*'
        state: absent
      when: promote_trigger_file_output.stdout | length > 0
  when:
    - pg_old_version|int <= 15 and pg_new_version|int >= 16

- block:  # vacuum_defer_cleanup_age (removed in the PG 16)
    # check if the vacuum_defer_cleanup_age parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'vacuum_defer_cleanup_age' parameter is specified"
      ansible.builtin.command: grep vacuum_defer_cleanup_age {{ patroni_config_file }}
      register: vacuum_defer_cleanup_age_output
      changed_when: false
      failed_when: false

    # if defined, remove the vacuum_defer_cleanup_age parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'vacuum_defer_cleanup_age'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)vacuum_defer_cleanup_age:.*'
        state: absent
      when: vacuum_defer_cleanup_age_output.stdout | length > 0
  when:
    - pg_old_version|int <= 15 and pg_new_version|int >= 16

- block:  # db_user_namespace (removed in the PG 17)
    # check if the db_user_namespace parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'db_user_namespace' parameter is specified"
      ansible.builtin.command: grep db_user_namespace {{ patroni_config_file }}
      register: db_user_namespace_output
      changed_when: false
      failed_when: false

    # if defined, remove the db_user_namespace parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'db_user_namespace'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)db_user_namespace:.*'
        state: absent
      when: db_user_namespace_output.stdout | length > 0
  when:
    - pg_old_version|int <= 16 and pg_new_version|int >= 17

- block:  # old_snapshot_threshold (removed in the PG 17)
    # check if the old_snapshot_threshold parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'old_snapshot_threshold' parameter is specified"
      ansible.builtin.command: grep old_snapshot_threshold {{ patroni_config_file }}
      register: old_snapshot_threshold_output
      changed_when: false
      failed_when: false

    # if defined, remove the old_snapshot_threshold parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'old_snapshot_threshold'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)old_snapshot_threshold:.*'
        state: absent
      when: old_snapshot_threshold_output.stdout | length > 0
  when:
    - pg_old_version|int <= 16 and pg_new_version|int >= 17

- block:  # trace_recovery_messages (removed in the PG 17)
    # check if the trace_recovery_messages parameter is specified in the patroni.yml
    - name: "Edit patroni.yml | check if the 'trace_recovery_messages' parameter is specified"
      ansible.builtin.command: grep trace_recovery_messages {{ patroni_config_file }}
      register: trace_recovery_messages_output
      changed_when: false
      failed_when: false

    # if defined, remove the trace_recovery_messages parameter from the patroni.yml
    - name: "Edit patroni.yml | remove parameter: 'trace_recovery_messages'"
      ansible.builtin.lineinfile:
        path: "{{ patroni_config_file }}"
        regexp: '^(\s*)trace_recovery_messages:.*'
        state: absent
      when: trace_recovery_messages_output.stdout | length > 0
  when:
    - pg_old_version|int <= 16 and pg_new_version|int >= 17

# TODO: Prepare the parameters for PostgreSQL 18 and etc.

# To support upgrades in the Patroni Standby Cluster.
- name: "Edit patroni.yml | remove parameter: standby_cluster (if exists)"
  ansible.builtin.replace:
    path: "{{ patroni_config_file }}"
    regexp: '^\s*standby_cluster:[^\n]*\n(.|\n)*?initdb:'
    replace: '  initdb:'

- name: "Remove 'standby_cluster' parameter from DCS (if exists)"
  ansible.builtin.command: patronictl -c {{ patroni_config_file }} edit-config -s standby_cluster=null --force
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"
  when: inventory_hostname in groups['primary']

# Copy the pg_hba.conf file to a new PostgreSQL to save pg_hba rules.
- name: "Copy pg_hba.conf to {{ pg_new_confdir }}"
  ansible.builtin.copy:
    src: "{{ pg_old_confdir }}/pg_hba.conf"
    dest: "{{ pg_new_confdir }}"
    owner: postgres
    mode: '0600'
    force: true
    remote_src: true

...
