---
- name: "Ensure TLS directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ tls_owner | default('postgres') }}"
    group: "{{ tls_owner | default('postgres') }}"
    mode: "0750"
  loop:
    - "{{ tls_privatekey_path | default('/etc/tls/server.key') | dirname }}"
    - "{{ tls_cert_path | default('/etc/tls/server.crt') | dirname }}"

- name: "Generate private TLS key {{ tls_privatekey_path | default('/etc/tls/server.key') }}"
  community.crypto.openssl_privatekey:
    path: "{{ tls_privatekey_path | default('/etc/tls/server.key') }}"
    owner: "{{ tls_owner | default('postgres') }}"
    group: "{{ tls_owner | default('postgres') }}"
    mode: "{{ tls_privatekey_mode | default('0400') }}"
    size: "{{ tls_privatekey_size | default(4096) }}"
    type: "{{ tls_privatekey_type | default('RSA') }}"

- name: "Generate self-signed TLS certificate {{ tls_cert_path | default('/etc/tls/server.crt') }}"
  community.crypto.x509_certificate:
    path: "{{ tls_cert_path | default('/etc/tls/server.crt') }}"
    privatekey_path: "{{ tls_privatekey_path | default('/etc/tls/server.key') }}"
    owner: "{{ tls_owner | default('postgres') }}"
    group: "{{ tls_owner | default('postgres') }}"
    mode: "{{ tls_cert_mode | default('0644') }}"
    provider: "{{ tls_cert_provider | default('selfsigned') }}"
    entrust_not_after: "{{ tls_cert_entrust_not_after | default('+3650d') }}"
