---
name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - distro: debian12
            tag: latest
            namespace: geerlingguy
          - distro: ubuntu2404
            tag: latest
            namespace: geerlingguy
          - distro: rockylinux9
            tag: latest
            namespace: geerlingguy
          - distro: almalinux9
            tag: latest
            namespace: glillico

    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make bootstrap-dev

      - name: Run Molecule tests
        run: make molecule-test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          IMAGE_DISTRO: ${{ matrix.config.distro }}
          IMAGE_TAG: ${{ matrix.config.tag }}
          IMAGE_NAMESPACE: ${{ matrix.config.namespace }}
