---
name: scheduled PostgreSQL (Debian 13)

on:
  schedule:
    - cron: "15 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'vitabaks' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: make bootstrap-dev

      - name: Run Molecule tests
        run: make molecule-test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          IMAGE_DISTRO: debian13
